CREATE TABLE [dbo].[AwbFile]
(
	[Id] BIGINT NOT NULL IDENTITY (1, 1),

	[AwbId] BIGINT NOT NULL,
	[TypeId] INT NOT NULL,

	[Name] NVARCHAR(320) NOT NULL,
	[Data] VARBINARY(MAX) NOT NULL

	CONSTRAINT [PK_dbo.AwbFile] PRIMARY KEY CLUSTERED ([Id] ASC)
)
GO