CREATE TABLE [dbo].[ClientContract]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[UpdateTimestamp] DATETIMEOFFSET NOT NULL DEFAULT(GETUTCDATE()),
	[ClientId] BIGINT NOT NULL,
	[Data]	VARBINARY (MAX)	NOT NULL,
	[Name]	NVARCHAR (320) NOT NULL,
)
GO

CREATE UNIQUE INDEX [IX_ClientContract_ClientId] ON [dbo].[ClientContract] ([ClientId])
GO
