//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alicargo.DataAccess.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alicargo.DataAccess.Contracts.Resources.EventType", typeof(EventType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is created.
        /// </summary>
        public static string ApplicationCreated {
            get {
                return ResourceManager.GetString("ApplicationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set state.
        /// </summary>
        public static string ApplicationSetState {
            get {
                return ResourceManager.GetString("ApplicationSetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance decreased.
        /// </summary>
        public static string BalanceDecreased {
            get {
                return ResourceManager.GetString("BalanceDecreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance increased.
        /// </summary>
        public static string BalanceIncreased {
            get {
                return ResourceManager.GetString("BalanceIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation canceled.
        /// </summary>
        public static string CalculationCanceled {
            get {
                return ResourceManager.GetString("CalculationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP file is uploaded.
        /// </summary>
        public static string CPFileUploaded {
            get {
                return ResourceManager.GetString("CPFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery bill file is uploaded.
        /// </summary>
        public static string DeliveryBillFileUploaded {
            get {
                return ResourceManager.GetString("DeliveryBillFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice file is uploaded.
        /// </summary>
        public static string InvoiceFileUploaded {
            get {
                return ResourceManager.GetString("InvoiceFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing file is uploaded.
        /// </summary>
        public static string PackingFileUploaded {
            get {
                return ResourceManager.GetString("PackingFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set date of cargo receipt.
        /// </summary>
        public static string SetDateOfCargoReceipt {
            get {
                return ResourceManager.GetString("SetDateOfCargoReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set sender.
        /// </summary>
        public static string SetSender {
            get {
                return ResourceManager.GetString("SetSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set transit reference.
        /// </summary>
        public static string SetTransitReference {
            get {
                return ResourceManager.GetString("SetTransitReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift file is uploaded.
        /// </summary>
        public static string SwiftFileUploaded {
            get {
                return ResourceManager.GetString("SwiftFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torg12 file is uploaded.
        /// </summary>
        public static string Torg12FileUploaded {
            get {
                return ResourceManager.GetString("Torg12FileUploaded", resourceCulture);
            }
        }
    }
}
