INSERT [dbo].[Country] ([Name_En], [Name_Ru], [Code], [Position]) VALUES 
(N'Abkhazia', N'Абхазия', N'AB', 108),
(N'Afghanistan', N'Афганистан', N'AF', 111),
(N'Aland Islands', N'Аландские острова', N'AX', 75),
(N'Albania', N'Албания', N'AL', 47),
(N'Algeria', N'Алжир', N'DZ', 238),
(N'American Samoa', N'Американское Самоа', N'AS', 218),
(N'Andorra', N'Андорра', N'AD', 239),
(N'Angola', N'Ангола', N'AO', 81),
(N'Anguilla', N'Ангилья', N'AI', 15),
(N'Antarctica', N'Антарктика', N'AQ', 119),
(N'Antigua and Barbuda', N'Антигуа и Барбуда', N'AG', 206),
(N'Argentina', N'Аргентина', N'AR', 12),
(N'Armenia', N'Армения', N'AM', 13),
(N'Aruba', N'Аруба', N'AW', 14),
(N'Australia', N'Австралия', N'AU', 8),
(N'Austria', N'Австрия', N'AT', 16),
(N'Azerbaijan', N'Азербайджан', N'AZ', 17),
(N'Azores', N'Азорские острова', N'PT', 18),
(N'Bahamas', N'Багамские Острова', N'BS', 19),
(N'Bahrain', N'Бахрейн', N'BH', 20),
(N'Bangladesh', N'Бангладеш', N'BD', 21),
(N'Barbados', N'Барбадос', N'BB', 22),
(N'Belarus', N'Беларусь', N'BY', 23),
(N'Belgium', N'Бельгия', N'BE', 24),
(N'Belize', N'Белиз', N'BZ', 25),
(N'Benin', N'Бенин', N'BJ', 26),
(N'Bermuda', N'Бермудские Острова', N'BM', 27),
(N'Bolivia', N'Боливия', N'BO', 28),
(N'Bosnia-Herzegovina', N'Босния и Герцеговина', N'BA', 29),
(N'Botswana', N'Ботсвана', N'BW', 30),
(N'Bouvet Island', N'Буве', N'BV', 31),
(N'Brazil', N'Бразилия', N'BR', 32),
(N'British Indian Ocean Territory', N'Британская территория в Индийском океане', N'IO', 33),
(N'Brunei Darussalam', N'Бруней', N'BN', 34),
(N'Bulgaria', N'Болгария', N'BG', 35),
(N'Burkina Faso', N'Буркина-Фасо', N'BF', 36),
(N'Burundi', N'Бурунди', N'BI', 37),
(N'Buthan', N'Бутан', N'BT', 38),
(N'Cambodia', N'Камбоджа', N'KH', 39),
(N'Cameroon', N'Камерун', N'CM', 40),
(N'Canada', N'Канада', N'CA', 41),
(N'Cape Verde', N'Кабо-Верде', N'CV', 42),
(N'Cayman Islands', N'Каймановы Острова', N'KY', 43),
(N'Central African Rep.', N'Центральноафриканская Республика', N'CF', 44),
(N'Chad', N'Чад', N'TD', 45),
(N'Chile', N'Чили', N'CL', 46),
(N'China', N'Китай', N'CN', 4),
(N'Christmas Island', N'Остров Рождества', N'CX', 48),
(N'Cocos (Keeling) Isl.', N'Кокосовые Острова', N'CC', 49),
(N'Colombia', N'Колумбия', N'CO', 50),
(N'Comoros', N'Коморские Острова', N'KM', 51),
(N'Cook Islands', N'Кука острова', N'CK', 52),
(N'Costa Rica', N'Коста-Рика', N'CR', 53),
(N'Croatia', N'Хорватия', N'HR', 54),
(N'Cuba', N'Куба', N'CU', 55),
(N'Cyprus', N'Кипр', N'CY', 56),
(N'Czech Republic', N'Чехия', N'CZ', 57),
(N'Democratic Republic of the Congo', N'Конго, Демократическая Республика', N'CD', 58),
(N'Denmark', N'Дания', N'DK', 59),
(N'Djibouti', N'Джибути', N'DJ', 60),
(N'Dominica', N'Доминика', N'DM', 61),
(N'Dominican Republic', N'Доминиканская Республика', N'DO', 62),
(N'East Timor', N'Восточный Тимор', N'TP', 63),
(N'Ecuador', N'Эквадор', N'EC', 64),
(N'Egypt', N'Египет', N'EG', 65),
(N'El Salvador', N'Сальвадор', N'SV', 66),
(N'Equatorial Guinea', N'Экваториальная Гвинея', N'GQ', 67),
(N'Eritrea', N'Эритрея', N'ER', 68),
(N'Estonia', N'Эстония', N'EE', 69),
(N'Ethiopia', N'Эфиопия', N'ET', 70),
(N'Falkland Islands', N'Фолклендские (Мальвинские) острова', N'FK', 71),
(N'Faroe Islands', N'Фарерские Острова', N'FO', 72),
(N'Fiji', N'Фиджи', N'FJ', 73),
(N'Finland', N'Финляндия', N'FI', 74),
(N'France', N'Франция', N'FR', 3),
(N'French Polynesia', N'Французская Полинезия', N'PF', 76),
(N'French Southern and Antarctic Lands', N'Французские Южные и Антарктические Территории', N'TF', 77),
(N'Gabon', N'Габон', N'GA', 78),
(N'Gambia', N'Гамбия', N'GM', 79),
(N'Georgia', N'Грузия', N'GE', 80),
(N'Germany', N'Германия', N'DE', 7),
(N'Ghana', N'Гана', N'GH', 82),
(N'Gibraltar', N'Гибралтар', N'GI', 83),
(N'Greece', N'Греция', N'GR', 84),
(N'Greenland', N'Гренландия', N'GL', 85),
(N'Grenada', N'Гренада', N'GD', 86),
(N'Guadeloupe (Fr.)', N'Гваделупа', N'GP', 87),
(N'Guam (US)', N'Гуам', N'GU', 88),
(N'Guatemala', N'Гватемала', N'GT', 89),
(N'Guernsey', N'Гернси', N'GG', 90),
(N'Guinea', N'Гвинея', N'GN', 91),
(N'Guinea Bissau', N'Гвинея-Бисау', N'GW', 92),
(N'Guyana', N'Гвиана', N'GY', 93),
(N'Guyana (Fr.)', N'Гайана', N'GF', 94),
(N'Haiti', N'Гаити', N'HT', 95),
(N'Heard Island and McDonald Islands', N'Острова Херд и Макдональд', N'HM', 96),
(N'Honduras', N'Гондурас', N'HN', 97),
(N'Hong Kong', N'Гонконг', N'HK', 98),
(N'Hungary', N'Венгрия', N'HU', 99),
(N'Iceland', N'Исландия', N'IS', 100),
(N'India', N'Индия', N'IN', 101),
(N'Indonesia', N'Индонезия', N'ID', 102),
(N'Iran', N'Иран', N'IR', 103),
(N'Iraq', N'Ирак', N'IQ', 104),
(N'Ireland', N'Ирландия', N'IE', 105),
(N'Isle of Man', N'Остров Мэн', N'IM', 106),
(N'Israel', N'Израиль', N'IL', 107),
(N'Italy', N'Италия', N'IT', 1),
(N'Ivory Coast', N'Кот-д''Ивуар', N'CI', 109),
(N'Jamaica', N'Ямайка', N'JM', 110),
(N'Japan', N'Япония', N'JP', 2),
(N'Jersey', N'Джерси', N'JE', 112),
(N'Jordan', N'Иордания', N'JO', 113),
(N'Kazachstan', N'Казахстан', N'KZ', 114),
(N'Kenya', N'Кения', N'KE', 115),
(N'Kirgistan', N'Кыргызстан', N'KG', 116),
(N'Kiribati', N'Кирибати', N'KI', 117),
(N'Korea (North)', N'Корея (Северная)', N'KP', 118),
(N'Korea (South)', N'Корея (Южная)', N'KR', 10),
(N'Kosovo', N'Косово', N'KO', 120),
(N'Kuwait', N'Кувейт', N'KW', 121),
(N'Laos', N'Лаос', N'LA', 122),
(N'Latvia', N'Латвия', N'LV', 123),
(N'Lebanon', N'Ливан', N'LB', 124),
(N'Lesotho', N'Лесото', N'LS', 125),
(N'Liberia', N'Либерия', N'LR', 126),
(N'Libya', N'Ливия', N'LY', 127),
(N'Liechtenstein', N'Лихтенштейн', N'LI', 128),
(N'Lithuania', N'Литва', N'LT', 129),
(N'Luxembourg', N'Люксембург', N'LU', 130),
(N'Macau', N'Аомынь', N'MO', 131),
(N'Madagascar', N'Мадагаскар', N'MG', 132),
(N'Malawi', N'Малави', N'MW', 133),
(N'Malaysia', N'Малайзия', N'MY', 134),
(N'Maldives', N'Мальдивы', N'MV', 135),
(N'Mali', N'Мали', N'ML', 136),
(N'Malta', N'Мальта', N'MT', 137),
(N'Marshall Islands', N'Маршалловы Острова', N'MH', 138),
(N'Martinique (Fr.)', N'Мартиника', N'MQ', 139),
(N'Mauritania', N'Мавритания', N'MR', 140),
(N'Mauritius', N'Маврикий', N'MU', 141),
(N'Mayotte', N'Майотта', N'YT', 142),
(N'Mexico', N'Мексика', N'MX', 143),
(N'Micronesia', N'Микронезия', N'FM', 144),
(N'Moldavia', N'Молдова', N'MD', 145),
(N'Monaco', N'Монако', N'MC', 146),
(N'Mongolia', N'Монголия', N'MN', 147),
(N'Montenegro', N'Черногория', N'ME', 148),
(N'Montserrat', N'Монтсеррат', N'MS', 149),
(N'Morocco', N'Морокко', N'MA', 150),
(N'Mozambique', N'Мозамбик', N'MZ', 151),
(N'Myanmar', N'Мьянма', N'MM', 152),
(N'Nagorno-Karabakh Republic', N'Нагорно-Карабахская Республика', N'NK', 153),
(N'Namibia', N'Намибия', N'NA', 154),
(N'Nauru', N'Науру', N'NR', 155),
(N'Nepal', N'Непал', N'NP', 156),
(N'Netherland Antilles', N'Антильские Острова', N'AN', 157),
(N'Netherlands', N'Нидерланды', N'NL', 158),
(N'New Caledonia (Fr.)', N'Новая Каледония', N'NC', 159),
(N'New Zealand', N'Новая Зеландия', N'NZ', 160),
(N'Nicaragua', N'Никарагуа', N'NI', 161),
(N'Niger', N'Нигер', N'NE', 162),
(N'Nigeria', N'Нигерия', N'NG', 163),
(N'Niue', N'Ниуэ', N'NU', 164),
(N'Norfolk Island', N'Норфолк', N'NF', 165),
(N'Northern Cyprus', N'Турецкая Республика Северного Кипра', N'NC', 166),
(N'Northern Mariana Isl.', N'Северные Марианские острова', N'MP', 167),
(N'Norway', N'Норвегия', N'NO', 168),
(N'Oman', N'Оман', N'OM', 169),
(N'Pakistan', N'Пакистан', N'PK', 170),
(N'Palau', N'Палау', N'PW', 171),
(N'Palestine', N'Палестина', N'PS', 172),
(N'Panama', N'Панама', N'PA', 173),
(N'Papua New', N'Папуа — Новая Гвинея', N'PG', 174),
(N'Paraguay', N'Парагвай', N'PY', 175),
(N'Peru', N'Перу', N'PE', 176),
(N'Philippines', N'Филиппины', N'PH', 177),
(N'Pitcairn', N'Питкэрн', N'PN', 178),
(N'Poland', N'Польша', N'PL', 179),
(N'Portugal', N'Португалия', N'PT', 180),
(N'Puerto Rico', N'Пуэрто-Рико', N'PR', 181),
(N'Qatar', N'Катар', N'QA', 182),
(N'Republic of Macedonia', N'Македония', N'MK', 183),
(N'Republic of Somaliland', N'Сомалиленд', N'S', 184),
(N'Republic of the Congo', N'Республика Конго', N'CG', 185),
(N'Reunion (Fr.)', N'Реюньон', N'RE', 186),
(N'Romania', N'Румыния', N'RO', 187),
(N'Russia', N'Россия', N'RU', 188),
(N'Rwanda', N'Руанда', N'RW', 189),
(N'Saint Lucia', N'Сент-Люсия', N'LC', 190),
(N'Samoa', N'Самоа', N'WS', 191),
(N'San Marino', N'Сан-Марино', N'SM', 192),
(N'Saudi Arabia', N'Саудовская Аравия', N'SA', 193),
(N'Senegal', N'Сенегал', N'SN', 194),
(N'Serbia', N'Сербия', N'RS', 195),
(N'Seychelles', N'Сейшельские острова', N'SC', 196),
(N'Sierra Leone', N'Сьерра-Леоне', N'SL', 197),
(N'Singapore', N'Сингапур', N'SG', 198),
(N'Slovak Republic', N'Словакия', N'SK', 199),
(N'Slovenia', N'Словения', N'SI', 200),
(N'Solomon Islands', N'Соломоновы Острова', N'SB', 201),
(N'Somalia', N'Сомали', N'SO', 202),
(N'South Africa', N'Южно-Африканская Республика', N'ZA', 203),
(N'South Georgia and the South Sandwich Islands', N'Южная Георгия и Южные Сандвичевы острова', N'GS', 204),
(N'South Ossetia', N'Южная Осетия', N'OS', 205),
(N'Spain', N'Испания', N'ES', 11),
(N'Sri Lanka', N'Шри-Ланка', N'LK', 207),
(N'St. Helena', N'Остров Святой Елены', N'SH', 208),
(N'St. Pierre & Miquelon', N'Сен-Пьер и Микелон', N'PM', 209),
(N'St. Tome and Principe', N'Сан-Томе и Принсипи', N'ST', 210),
(N'St.Kitts Nevis Anguilla', N'Сент-Киттс и Невис', N'KN', 211),
(N'St.Vincent & Grenadines', N'Сент-Винсент и Гренадины', N'VC', 212),
(N'Sudan', N'Судан', N'SD', 213),
(N'Suriname', N'Суринам', N'SR', 214),
(N'Svalbard & Jan Mayen Is', N'Свальбард', N'SJ', 215),
(N'Swaziland', N'Свазиленд', N'SZ', 216),
(N'Sweden', N'Швеция', N'SE', 217),
(N'Switzerland', N'Швейцария', N'CH', 6),
(N'Syria', N'Сирия', N'SY', 219),
(N'Tadjikistan', N'Таджикистан', N'TJ', 220),
(N'Taiwan', N'Тайвань', N'TW', 221),
(N'Tamil Eelam', N'Тамил-Илам', N'TE', 222),
(N'Tanzania', N'Танзания', N'TZ', 223),
(N'Thailand', N'Таиланд', N'TH', 224),
(N'Togo', N'Того', N'TG', 225),
(N'Tokelau', N'Токелау', N'TK', 226),
(N'Tonga', N'Тонга', N'TO', 227),
(N'Transnistria', N'Приднестровье', N'TS', 228),
(N'Trinidad & Tobago', N'Тринидад и Тобаго', N'TT', 229),
(N'Tunisia', N'Тунис', N'TN', 230),
(N'Turkey', N'Турция', N'TR', 231),
(N'Turkmenistan', N'Туркменистан', N'TM', 232),
(N'Turks and Caicos Islands', N'Тёркс и Кайкос', N'TC', 233),
(N'Tuvalu', N'Тувалу', N'TV', 234),
(N'Uganda', N'Уганда', N'UG', 235),
(N'Ukraine', N'Украина', N'UA', 236),
(N'United Arab Emirates', N'Объединенные Арабские Эмираты', N'AE', 237),
(N'United Kingdom (Great Britain)', N'Великобритания', N'GB', 5),
(N'United States', N'Соединенные Штаты Америки', N'US', 239),
(N'United States Minor Outlying Islands', N'Внешние малые острова (США)', N'UM', 240),
(N'Uruguay', N'Уругвай', N'UY', 241),
(N'Uzbekistan', N'Узбекистан', N'UZ', 242),
(N'Vanuatu', N'Вануату', N'VU', 243),
(N'Vatican City State', N'Ватикан', N'VA', 244),
(N'Venezuela', N'Венесуэла', N'VE', 245),
(N'Vietnam', N'Вьетнам', N'VN', 246),
(N'Virgin Islands (British)', N'Виргинские Острова (Британские)', N'VG', 247),
(N'Virgin Islands (US)', N'Виргинские Острова (США)', N'VI', 248),
(N'Wallis & Futuna Islands', N'Острова Уоллис и Футуна', N'WF', 249),
(N'Western Sahara', N'Западная Сахара', N'EH', 250),
(N'Yemen', N'Йемен', N'YE', 251),
(N'Zambia', N'Замбия', N'ZM', 252),
(N'Zimbabwe', N'Зимбабве', N'ZW', 253)
GO