//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alicargo.Core.Resources {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alicargo.Core.Resources.Entities", typeof(Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional cost (€).
        /// </summary>
        public static string AdditionalCost {
            get {
                return ResourceManager.GetString("AdditionalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of a cargo unload.
        /// </summary>
        public static string AddressLoad {
            get {
                return ResourceManager.GetString("AddressLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air waybill.
        /// </summary>
        public static string AirWaybill {
            get {
                return ResourceManager.GetString("AirWaybill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аrrival airport.
        /// </summary>
        public static string ArrivalAirport {
            get {
                return ResourceManager.GetString("ArrivalAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB.
        /// </summary>
        public static string AWB {
            get {
                return ResourceManager.GetString("AWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        public static string BIC {
            get {
                return ResourceManager.GetString("BIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        public static string Broker {
            get {
                return ResourceManager.GetString("Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker cost (€).
        /// </summary>
        public static string BrokerCost {
            get {
                return ResourceManager.GetString("BrokerCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost of the broker per kg (€).
        /// </summary>
        public static string BrokerCostPerKg {
            get {
                return ResourceManager.GetString("BrokerCostPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string CarrierName {
            get {
                return ResourceManager.GetString("CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics of the goods.
        /// </summary>
        public static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the new password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost per kilogram for Sender (€).
        /// </summary>
        public static string CostPerKgOfSender {
            get {
                return ResourceManager.GetString("CostPerKgOfSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial invoice.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreationTimestamp {
            get {
                return ResourceManager.GetString("CreationTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom cost (€).
        /// </summary>
        public static string CustomCost {
            get {
                return ResourceManager.GetString("CustomCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs clearance per kg (€).
        /// </summary>
        public static string CustomCostPerKg {
            get {
                return ResourceManager.GetString("CustomCostPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of receipt to a warehouse.
        /// </summary>
        public static string DateInStock {
            get {
                return ResourceManager.GetString("DateInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of arrival.
        /// </summary>
        public static string DateOfArrival {
            get {
                return ResourceManager.GetString("DateOfArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of cargo receipt.
        /// </summary>
        public static string DateOfCargoReceipt {
            get {
                return ResourceManager.GetString("DateOfCargoReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of departure.
        /// </summary>
        public static string DateOfDeparture {
            get {
                return ResourceManager.GetString("DateOfDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in work.
        /// </summary>
        public static string DaysInWork {
            get {
                return ResourceManager.GetString("DaysInWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery bill.
        /// </summary>
        public static string DeliveryBill {
            get {
                return ResourceManager.GetString("DeliveryBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery type.
        /// </summary>
        public static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure airport.
        /// </summary>
        public static string DepartureAirport {
            get {
                return ResourceManager.GetString("DepartureAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application number.
        /// </summary>
        public static string DisplayNumber {
            get {
                return ResourceManager.GetString("DisplayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable email sending.
        /// </summary>
        public static string EnableEmailSend {
            get {
                return ResourceManager.GetString("EnableEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory contacts.
        /// </summary>
        public static string FactoryContact {
            get {
                return ResourceManager.GetString("FactoryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory email.
        /// </summary>
        public static string FactoryEmail {
            get {
                return ResourceManager.GetString("FactoryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string FactoryName {
            get {
                return ResourceManager.GetString("FactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory phone.
        /// </summary>
        public static string FactoryPhone {
            get {
                return ResourceManager.GetString("FactoryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture (€).
        /// </summary>
        public static string FactureCost {
            get {
                return ResourceManager.GetString("FactureCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture* (€).
        /// </summary>
        public static string FactureCostEdited {
            get {
                return ResourceManager.GetString("FactureCostEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight cost (€).
        /// </summary>
        public static string FlightCost {
            get {
                return ResourceManager.GetString("FlightCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fare per kg (€).
        /// </summary>
        public static string FlightCostPerKg {
            get {
                return ResourceManager.GetString("FlightCostPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTD.
        /// </summary>
        public static string GTD {
            get {
                return ResourceManager.GetString("GTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTD-extended.
        /// </summary>
        public static string GTDAdditional {
            get {
                return ResourceManager.GetString("GTDAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INN.
        /// </summary>
        public static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPP.
        /// </summary>
        public static string KPP {
            get {
                return ResourceManager.GetString("KPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correspondent account.
        /// </summary>
        public static string KS {
            get {
                return ResourceManager.GetString("KS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal address.
        /// </summary>
        public static string LegalAddress {
            get {
                return ResourceManager.GetString("LegalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity.
        /// </summary>
        public static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized name.
        /// </summary>
        public static string LocalizedName {
            get {
                return ResourceManager.GetString("LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address.
        /// </summary>
        public static string MailingAddress {
            get {
                return ResourceManager.GetString("MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of delivery.
        /// </summary>
        public static string MethodOfDelivery {
            get {
                return ResourceManager.GetString("MethodOfDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of transit.
        /// </summary>
        public static string MethodOfTransit {
            get {
                return ResourceManager.GetString("MethodOfTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify another carrier.
        /// </summary>
        public static string NewCarrierName {
            get {
                return ResourceManager.GetString("NewCarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC.
        /// </summary>
        public static string Nic {
            get {
                return ResourceManager.GetString("Nic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office phone.
        /// </summary>
        public static string OfficePhone {
            get {
                return ResourceManager.GetString("OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRN.
        /// </summary>
        public static string OGRN {
            get {
                return ResourceManager.GetString("OGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up (€).
        /// </summary>
        public static string PickupCost {
            get {
                return ResourceManager.GetString("PickupCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up* (€).
        /// </summary>
        public static string PickupCostEdited {
            get {
                return ResourceManager.GetString("PickupCostEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Delivery.
        /// </summary>
        public static string PriceForDelivery {
            get {
                return ResourceManager.GetString("PriceForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit (€).
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profit kg (€).
        /// </summary>
        public static string ProfitPerKg {
            get {
                return ResourceManager.GetString("ProfitPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current account.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tape (€).
        /// </summary>
        public static string ScotchCost {
            get {
                return ResourceManager.GetString("ScotchCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tape* (€).
        /// </summary>
        public static string ScotchCostEdited {
            get {
                return ResourceManager.GetString("ScotchCostEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate sender euro/kg.
        /// </summary>
        public static string SenderRate {
            get {
                return ResourceManager.GetString("SenderRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the state .
        /// </summary>
        public static string StateChangeTimestamp {
            get {
                return ResourceManager.GetString("StateChangeTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian name.
        /// </summary>
        public static string StateItalianName {
            get {
                return ResourceManager.GetString("StateItalianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next state.
        /// </summary>
        public static string StateNextName {
            get {
                return ResourceManager.GetString("StateNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian name.
        /// </summary>
        public static string StateRussianName {
            get {
                return ResourceManager.GetString("StateRussianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        public static string Swift {
            get {
                return ResourceManager.GetString("Swift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff for tape (€/box).
        /// </summary>
        public static string TariffOfTapePerBox {
            get {
                return ResourceManager.GetString("TariffOfTapePerBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarif per kg (€).
        /// </summary>
        public static string TariffPerKg {
            get {
                return ResourceManager.GetString("TariffPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of delivery.
        /// </summary>
        public static string TermsOfDelivery {
            get {
                return ResourceManager.GetString("TermsOfDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TORG 12.
        /// </summary>
        public static string Torg12 {
            get {
                return ResourceManager.GetString("Torg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs by weight (€).
        /// </summary>
        public static string TotalCostOfSenderForWeight {
            get {
                return ResourceManager.GetString("TotalCostOfSenderForWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total costs (€).
        /// </summary>
        public static string TotalExpenses {
            get {
                return ResourceManager.GetString("TotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sender (€).
        /// </summary>
        public static string TotalOfSender {
            get {
                return ResourceManager.GetString("TotalOfSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit (total, €).
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total cost of tape (€).
        /// </summary>
        public static string TotalScotchCost {
            get {
                return ResourceManager.GetString("TotalScotchCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total sender costs.
        /// </summary>
        public static string TotalSenderRate {
            get {
                return ResourceManager.GetString("TotalSenderRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum (€).
        /// </summary>
        public static string TotalTariffCost {
            get {
                return ResourceManager.GetString("TotalTariffCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost of the forwarder (total, €).
        /// </summary>
        public static string TotalTransitCost {
            get {
                return ResourceManager.GetString("TotalTransitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery (€).
        /// </summary>
        public static string TransitCost {
            get {
                return ResourceManager.GetString("TransitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery* (€).
        /// </summary>
        public static string TransitCostEdited {
            get {
                return ResourceManager.GetString("TransitCostEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit AirWaybill.
        /// </summary>
        public static string TransitReference {
            get {
                return ResourceManager.GetString("TransitReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of the warehouse.
        /// </summary>
        public static string WarehouseWorkingTime {
            get {
                return ResourceManager.GetString("WarehouseWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
