// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Alicargo.Controllers
{
    public partial class TransitController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TransitController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EditByApplication()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EditByApplication);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EditByClient()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EditByClient);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TransitController Actions { get { return MVC.Transit; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Transit";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Transit";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string EditByApplication = "EditByApplication";
            public readonly string EditByClient = "EditByClient";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string EditByApplication = "EditByApplication";
            public const string EditByClient = "EditByClient";
        }


        static readonly ActionParamsClass_EditByApplication s_params_EditByApplication = new ActionParamsClass_EditByApplication();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditByApplication EditByApplicationParams { get { return s_params_EditByApplication; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditByApplication
        {
            public readonly string applicationId = "applicationId";
        }
        static readonly ActionParamsClass_EditByClient s_params_EditByClient = new ActionParamsClass_EditByClient();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditByClient EditByClientParams { get { return s_params_EditByClient; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditByClient
        {
            public readonly string clientId = "clientId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditByApplication = "EditByApplication";
                public readonly string EditByClient = "EditByClient";
            }
            public readonly string EditByApplication = "~/Views/Transit/EditByApplication.cshtml";
            public readonly string EditByClient = "~/Views/Transit/EditByClient.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string TransitEditModel = "TransitEditModel";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TransitController : Alicargo.Controllers.TransitController
    {
        public T4MVC_TransitController() : base(Dummy.Instance) { }

        [NonAction]
        partial void EditByApplicationOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, long? applicationId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EditByApplication(long? applicationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EditByApplication);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "applicationId", applicationId);
            EditByApplicationOverride(callInfo, applicationId);
            return callInfo;
        }

        [NonAction]
        partial void EditByClientOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, long? clientId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EditByClient(long? clientId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EditByClient);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clientId", clientId);
            EditByClientOverride(callInfo, clientId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
