CREATE PROCEDURE [dbo].[Bill_AddOrReplace]
	@ApplicationId BIGINT,
	@Number INT,
	@Bank NVARCHAR(MAX),
	@BIC NVARCHAR(MAX),
	@CorrespondentAccount NVARCHAR(MAX),
	@TIN NVARCHAR(MAX),
	@TaxRegistrationReasonCode NVARCHAR(MAX),
	@CurrentAccount NVARCHAR(MAX),
	@Payee NVARCHAR(MAX),
	@Shipper NVARCHAR(MAX),
	@Head NVARCHAR(MAX),
	@Accountant NVARCHAR(MAX),
	@HeaderText NVARCHAR(MAX),
	@Client NVARCHAR(MAX),
	@Goods NVARCHAR(MAX),
	@Count SMALLINT,
	@Price MONEY,
	@VAT MONEY,
	@EuroToRuble MONEY,
	@SaveDate DATETIMEOFFSET,
	@SendDate DATETIMEOFFSET

AS BEGIN
	SET NOCOUNT ON;

	MERGE [dbo].[Bill] AS target
		USING (SELECT @ApplicationId,
					@Number,
					@Bank,
					@BIC,
					@CorrespondentAccount,
					@TIN,
					@TaxRegistrationReasonCode,
					@CurrentAccount,
					@Payee,
					@Shipper,
					@Head,
					@Accountant,
					@HeaderText,
					@Client,
					@Goods,
					@Count,
					@Price,
					@VAT,
					@EuroToRuble,
					@SaveDate,
					@SendDate)
			AS source ([ApplicationId],
					[Number],
					[Bank],
					[BIC],
					[CorrespondentAccount],
					[TIN],
					[TaxRegistrationReasonCode],
					[CurrentAccount],
					[Payee],
					[Shipper],
					[Head],
					[Accountant],
					[HeaderText],
					[Client],
					[Goods],
					[Count],
					[Price],
					[VAT],
					[EuroToRuble],
					[SaveDate],
					[SendDate])
			ON (target.[ApplicationId] = source.[ApplicationId])
		WHEN MATCHED THEN 
			UPDATE SET [Bank] = source.[Bank],
						[Number] = source.[Number],
						[BIC] = source.[BIC],
						[CorrespondentAccount] = source.[CorrespondentAccount],
						[TIN] = source.[TIN],
						[TaxRegistrationReasonCode] = source.[TaxRegistrationReasonCode],
						[CurrentAccount] = source.[CurrentAccount],
						[Payee] = source.[Payee],
						[Shipper] = source.[Shipper],
						[Head] = source.[Head],
						[Accountant] = source.[Accountant],
						[HeaderText] = source.[HeaderText],
						[Client] = source.[Client],
						[Goods] = source.[Goods],
						[Count] = source.[Count],
						[Price] = source.[Price],
						[VAT] = source.[VAT],
						[EuroToRuble] = source.[EuroToRuble],
						[SaveDate] = source.[SaveDate],
						[SendDate] = source.[SendDate]
		WHEN NOT MATCHED THEN
			INSERT ([ApplicationId],
					[Number],
					[Bank],
					[BIC],
					[CorrespondentAccount],
					[TIN],
					[TaxRegistrationReasonCode],
					[CurrentAccount],
					[Payee],
					[Shipper],
					[Head],
					[Accountant],
					[HeaderText],
					[Client],
					[Goods],
					[Count],
					[Price],
					[VAT],
					[EuroToRuble],
					[SaveDate],
					[SendDate])
			VALUES (source.[ApplicationId],
					source.[Number],
					source.[Bank],
					source.[BIC],
					source.[CorrespondentAccount],
					source.[TIN],
					source.[TaxRegistrationReasonCode],
					source.[CurrentAccount],
					source.[Payee],
					source.[Shipper],
					source.[Head],
					source.[Accountant],
					source.[HeaderText],
					source.[Client],
					source.[Goods],
					source.[Count],
					source.[Price],
					source.[VAT],
					source.[EuroToRuble],
					source.[SaveDate],
					source.[SendDate])
		OUTPUT INSERTED.[Id];
END
GO