CREATE TABLE [dbo].[City]
(
	[Id] BIGINT NOT NULL IDENTITY (1, 1),
	[Name_En] NVARCHAR(128) NOT NULL,
	[Name_Ru] NVARCHAR(128) NOT NULL,
	[Position] INT NOT NULL, 

	CONSTRAINT [PK_dbo.City] PRIMARY KEY CLUSTERED ([Id] ASC)
)
GO