CREATE TABLE [dbo].[EmailMessage]
(
	[Id] BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[RowVersion] ROWVERSION NOT NULL,
	[StateId] INT NOT NULL,
	[StateIdTimestamp] DATETIMEOFFSET DEFAULT (GETUTCDATE()) NOT NULL,

	[From] NVARCHAR (MAX) NOT NULL,
	[To] NVARCHAR (MAX) NOT NULL,
	[CopyTo] NVARCHAR (MAX) NULL,
	[Subject] NVARCHAR (MAX) NOT NULL,
	[Body] NVARCHAR (MAX) NOT NULL,
	[Files] VARBINARY (MAX) NULL
)