CREATE TABLE [dbo].[Bill]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[ApplicationHistoryId]	BIGINT NOT NULL,
	[Bank] NVARCHAR(MAX) NOT NULL,
	[BIC] NVARCHAR(MAX) NOT NULL,
	[CorrespondentAccount] NVARCHAR(MAX) NOT NULL,
	[TIN] NVARCHAR(MAX) NOT NULL,
	[TaxRegistrationReasonCode] NVARCHAR(MAX) NOT NULL,
	[CurrentAccount] NVARCHAR(MAX) NOT NULL,
	[Payee] NVARCHAR(MAX) NOT NULL,
	[Shipper] NVARCHAR(MAX) NOT NULL,
	[Head] NVARCHAR(MAX) NOT NULL,
	[Accountant] NVARCHAR(MAX) NOT NULL,
	[HeaderText] NVARCHAR(MAX) NOT NULL
)
