CREATE TABLE [dbo].[Event]
(
	[Id] BIGINT IDENTITY(1, 1) NOT NULL,

	[StateId] INT NOT NULL,
	[StateIdTimestamp] DATETIMEOFFSET CONSTRAINT [DF_Event_StateIdTimestamp] DEFAULT (GETUTCDATE()) NOT NULL,
	[PartitionId] INT NOT NULL,

	[EventTypeId] INT NOT NULL,
	[Data] VARBINARY(MAX) NULL,
	[UserId] BIGINT NULL,

	CONSTRAINT [PK_dbo.Event] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.Event_dbo.User_Id] FOREIGN KEY 
		([UserId]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE
)
GO